# Generated by Django 3.0.4 on 2020-04-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('todo', '0008_auto_20200405_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
            preserve_default=False,
        ),
    ]
