# Generated by Django 3.0.4 on 2020-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
